# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfc1d928c0b4c28d0a50b5a127e3ec17ca057a07fb105ca3e6e5e112572ad9fd46d933935e536e1eb3c2d7e22268fd4545306a26193dbf353dd2af4862035b15

test:
  secret_key_base: 9cd639e2524cd4483c06e0baabccce9c5e4931a1329a3e8470b7947be580349062e3a5107bab031821a97da712ebb70607e0bed3c43069c7dd62a012c5e93090

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
